apiVersion: apps/v1
kind: Deployment
metadata:
  name: smap-identity-consumer
  namespace: smap
  labels:
    app: smap-identity-consumer
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: smap-identity-consumer
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smap-identity-consumer
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: smap-identity-consumer
        image: registry.tantai.dev/smap/smap-identity-consumer:251124-000539
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: HOST
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: APP_PORT
        - name: API_MODE
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: API_MODE
        - name: LOGGER_LEVEL
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: LOGGER_LEVEL
        - name: LOGGER_MODE
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: LOGGER_MODE
        - name: LOGGER_ENCODING
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: LOGGER_ENCODING
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: POSTGRES_DB
        - name: POSTGRES_SSLMODE
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: POSTGRES_SSLMODE
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: RABBITMQ_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: JWT_SECRET
        - name: ENCRYPT_KEY
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: ENCRYPT_KEY
        - name: INTERNAL_KEY
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: INTERNAL_KEY
        - name: DISCORD_WEBHOOK_ID
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: DISCORD_WEBHOOK_ID
        - name: DISCORD_WEBHOOK_TOKEN
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: DISCORD_WEBHOOK_TOKEN
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: SMTP_PORT
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smap-identity-secrets
              key: SMTP_PASSWORD
        - name: SMTP_FROM
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: SMTP_FROM
        - name: SMTP_FROM_NAME
          valueFrom:
            configMapKeyRef:
              name: smap-identity-config
              key: SMTP_FROM_NAME
        - name: CONTAINER_NAME
          value: "smap-identity-consumer"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

